# Generated by Django 2.1.7 on 2021-10-05 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20211005_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(blank=True, default=datetime.datetime(2021, 10, 5, 6, 39, 17, 272189)),
        ),
    ]
